### ISSUE TITLE
Reflutter not work on dart updated version

### ISSUE THREAD

**Issue by digitalocean-droplet** [Impact-I/reFlutter#302]
Could you please help me to check , i'm doubt that reflutter not work on dart updated version , which is 

`Dart version: 3.5.0, Snapshot: 80a49c7111088100a233b2ae788e1f48`

When i did with reflutter , can't see any traffic and can't see dump.dart in application's data file.

Thanks

**Comment by frankl1m** [comment]
Still without work

**Comment by frankl1m** [comment]
HASH d20a1be77c3d3c41b2a5accaee1ce549, TLS close connection

**Comment by larrypaul93** [comment]
i generated custom build just disabling ssl cert verification, so it will work with system proxy, like using http tool kit
[http://bashupload.com/ademt/libflutter.so](libflutter.so)

**Comment by thanhvd-metric** [comment]
> i generated custom build just disabling ssl cert verification, so it will work with system proxy, like using http tool kit [http://bashupload.com/ademt/libflutter.so](libflutter.so)

hi @larrypaul93 I'm facing same problem. I accessed the link you provided and unfortunately there is no file left there. seems like bashupload.com only allow a file to be downloaded once. Can you reupload it somewhere else? Thank you so much

**Comment by digitalocean-droplet** [comment]
hello @jayluxferro , may i know any update on this issue. please let me know if u need anything from me , i here to provide whatever u need. thanks .

**Comment by larrypaul93** [comment]
[libflutter.so.zip](https://github.com/user-attachments/files/17082814/libflutter.so.zip)

**Comment by jayluxferro** [comment]
Hi @godhellolaypr , it should be resolved in the next 24 hours

**Comment by LastPlayerTR** [comment]
Still not capturing traffic and bypassing ssl.

Thank you @larrypaul93 libflutter working.

**Comment by frankl1m** [comment]
wich arch is this libflutter?

> [libflutter.so.zip](https://github.com/user-attachments/files/17082814/libflutter.so.zip)

**Comment by jayluxferro** [comment]
@godhellolaypr @frankl1m @thanhvd-metric issue resolved now.

**Comment by frankl1m** [comment]
Have any library for x86 or x64

**Comment by jayluxferro** [comment]
@frankl1m you can use the custom build for x86-64 library

https://github.com/Impact-I/reFlutter?tab=readme-ov-file#custom-build

**Comment by frankl1m** [comment]
HASH d20a1be77c3d3c41b2a5accaee1ce549, still TLS close connection reflutter and your libflutter.so still crashing the app

**Comment by jayluxferro** [comment]
> HASH d20a1be77c3d3c41b2a5accaee1ce549, still TLS close connection reflutter and your libflutter.so still crashing the app

This issue has nothing to do with reflutter

**Comment by rewhex** [comment]
I have the same error with the d20a1be77c3d3c41b2a5accaee1ce549, please help @jayluxferro

**Comment by TheAndrey** [comment]
I have some issues with that snapshot hash. Target app doesn't connect to server after patching.

Everything used to work (on `7dbbeeb8ef7b91338640dca3927636de`) until the developer released a new version of the app.

**Comment by rewhex** [comment]
@jayluxferro I've tried to make a custom build using instructions from the README, but faced this issue - https://github.com/Impact-I/reFlutter/issues/260

**Comment by jayluxferro** [comment]
> @jayluxferro I've tried to make a custom build using instructions from the README, but faced this issue - #260

Share a screenshot of the error you're getting.

**Comment by rewhex** [comment]
@jayluxferro 
It's the same as in the #260 :
`USAGE:`
`reflutter your.(apk)|(ipa)`
`Wait... Change the source code...`
`src/build/install-build-deps-android.sh: not found`

**Comment by jayluxferro** [comment]
> @jayluxferro It's the same as in the #260 : `USAGE:` `reflutter your.(apk)|(ipa)` `Wait... Change the source code...` `src/build/install-build-deps-android.sh: not found`

Please share the snapshot_hash and engine_commit_hash you used

**Comment by rewhex** [comment]
@jayluxferro 
hash: d20a1be77c3d3c41b2a5accaee1ce549
commit: f6344b75dcf861d8bf1f1322780b8811f982e31a

**Comment by rewhex** [comment]
Also I see a few more errors in Dockerfile:
1. Both `reflutter $HASH_PATCH -l` returns `USAGE: reflutter your.(apk)|(ipa)` and exits with the exception
2. Some (git?) command returns `error: unknown option `type'`, `usage: git config [<options>]`
3. And finally the issue I told you above (check screenshot)

<img width="477" alt="Screenshot 2024-10-06 at 10 20 16 PM" src="https://github.com/user-attachments/assets/0f50cd7e-7910-455a-a77b-676e89d8b05e">

Also I can't understand why patching the apk with d20a1be77c3d3c41b2a5accaee1ce549 .so file from releases page isn't working,  after I enable traffic intercepting, BurpSuite still shows me handshake failure, like certificate pinning is still active.

**Comment by jayluxferro** [comment]
> Also I see a few more errors in Dockerfile:
> 
> 1. Both `reflutter $HASH_PATCH -l` returns `USAGE: reflutter your.(apk)|(ipa)` and exits with the exception
> 2. Some (git?) command returns `error: unknown option `type'`, `usage: git config []`
> 3. And finally the issue I told you above (check screenshot)
> 
> <img alt="Screenshot 2024-10-06 at 10 20 16 PM" width="477" src="https://private-user-images.githubusercontent.com/26175102/373970355-0f50cd7e-7910-455a-a77b-676e89d8b05e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNDIwNzEsIm5iZiI6MTcyODI0MTc3MSwicGF0aCI6Ii8yNjE3NTEwMi8zNzM5NzAzNTUtMGY1MGNkN2UtNzkxMC00NTVhLWE3N2ItNjc2ZTg5ZDhiMDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE5MDkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MTZkZGRhNmNmZWI2MDRmOWU2NWEzMmJkZGFjZmQ4OTg3NzQ2YWViYjNlNTc5NDg5OTRjMWRiMDdjNDZkODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qD8Czc6RZFjheM56bo_-g48GlEH3WRc3LxSiS_7IlBI">
> Also I can't understand why patching the apk with d20a1be77c3d3c41b2a5accaee1ce549 .so file from releases page isn't working, after I enable traffic intercepting, BurpSuite still shows me handshake failure, like certificate pinning is still active.

Looking into it.

**Comment by rewhex** [comment]
@jayluxferro Seems like this errors is because Docker image is too old (3 years), if I run commands like in the github actions they work as expected.

Edit: Just found out scripts/build-engine file. README file says to use docker, but actually we can build custom libflutter.so with the `cd scripts && ./build-engine` 😧

**Comment by rewhex** [comment]
Found the error.
`src/third_party/boringssl/src/ssl/ssl_x509.cc` path is now:
`src/flutter/third_party/boringssl/src/ssl/ssl_x509.cc`

**Comment by jayluxferro** [comment]
> Found the error. `src/third_party/boringssl/src/ssl/ssl_x509.cc` path is now: `src/flutter/third_party/boringssl/src/ssl/ssl_x509.cc`

Seen. Already pushed a fix for that: https://github.com/Impact-I/reFlutter/blob/8010588f7df8e890e57b9731ac3a3a7f8355d53c/src/__init__.py#L335

workflow now building.

**Comment by rewhex** [comment]
@jayluxferro Thank you! This was fast.
I've to say, there is maybe another problem with string replace. If you look closer, the lines doesn't match because the whitespace is changed in that file too.
(last string is added by me)

https://github.com/user-attachments/assets/a8636eea-1f09-47a9-ad8c-1fb90956dced

**Comment by jayluxferro** [comment]
> @jayluxferro Thank you! This was fast. I've to say, there is maybe another problem with string replace. If you look closer, the lines doesn't match because the whitespace is changed in that file too. (last string is added by me)
> 
>  Screen.Recording.2024-10-07.at.12.58.23.AM.mov

I already fixed that. It's in the same PR

**Comment by jayluxferro** [comment]
Issue should be fixed now

**Comment by TheAndrey** [comment]
Thanks! It works now.
